roughpy/src/args/strided_copy.cpp
roughpy/src/args/strided_copy.h
roughpy/src/scalars/parse_key_scalar_stream.cpp
tests/streams/test_lie_increment_path.py

Fix a bug in the creation of a `LieIncrementStream` from an array of (NumPy) integer arrays. Closes #30 .

Fix Lie increment stream from int array

---

algebra/include/roughpy/algebra/basis.h
algebra/include/roughpy/algebra/basis_impl.h
algebra/src/libalgebra_lite_internal/lie_basis_info.h
algebra/src/libalgebra_lite_internal/tensor_basis_info.h
roughpy/src/algebra/lie_key.cpp
roughpy/src/algebra/lie_key_iterator.cpp
tests/algebra/test_lie_basis.py

Fixed a bug in the Lie key iterator that caused keys to be represented incorrectly. Closes #40 .

Fix lie key iterator

---

CMakeLists.txt
roughpy/CMakeLists.txt
scalars/CMakeLists.txt
scalars/scalar_blas_defs.h.in
scalars/src/linear_algebra/blas.h
scalars/src/linear_algebra/blas_complex_double.cpp
scalars/src/linear_algebra/blas_complex_float.cpp
scalars/src/linear_algebra/blas_double.cpp
scalars/src/linear_algebra/blas_float.cpp
scalars/src/linear_algebra/lapack.h
scalars/src/linear_algebra/lapack_complex_double.cpp
scalars/src/linear_algebra/lapack_complex_float.cpp
scalars/src/linear_algebra/lapack_double.cpp
scalars/src/linear_algebra/lapack_float.cpp
scalars/src/scalar_blas_impl.h
scalars/src/scalar_implementations/double/double_lin_alg.cpp
scalars/src/scalar_implementations/double/double_lin_alg.h
scalars/src/scalar_implementations/double/double_type.cpp
scalars/src/scalar_implementations/double/double_type.h
scalars/src/scalar_implementations/float/float_blas.cpp
scalars/src/scalar_implementations/float/float_blas.h
scalars/src/scalar_implementations/float/float_type.cpp
scalars/src/scalar_implementations/float/float_type.h
scalars/src/standard_linalg.h
scalars/src/test_float_blas.cpp

Added cmake option to disable generation of BLAS bindings,  and provided a temporary workaround to a bug in vcpkg that causes some cmake variables to be unset.

Disable blas

---

CHANGELOG
algebra/include/roughpy/algebra/algebra_base.h
algebra/include/roughpy/algebra/algebra_base_impl.h
device/CMakeLists.txt
device/include/roughpy/device/core.h
device/src/core.cpp
roughpy/src/algebra/free_tensor.cpp
roughpy/src/algebra/setup_algebra_type.h
roughpy/src/args/numpy.cpp
roughpy/src/args/numpy.h
roughpy/src/roughpy_module.cpp
roughpy/src/scalars/r_py_polynomial.cpp
roughpy/src/scalars/r_py_polynomial.h
roughpy/src/scalars/scalars.cpp
roughpy/src/scalars/scalars.h
scalars/include/roughpy/scalars/scalar.h
scalars/src/scalar.cpp
scalars/src/types/aprational/ap_rational_type.cpp
scalars/src/types/aprational/ap_rational_type.h
tests/algebra/test_free_tensor.py

Changed the behaviour of the __array__ method for algebra types. A copy is always returned of the correct size.

Fix conversion to numpy

---

roughpy/src/args/strided_copy.cpp
roughpy/src/scalars/parse_key_scalar_stream.cpp
tests/streams/test_lie_increment_path.py

Fix a bug when constructing streams that caused stream increment arrays with larger width than number of increments to be transposed.

do not transpose arrays that are wide but short for streams

---

vcpkg-configuration.json

Hopefully this should enforce relative lookup of the vcpkg registry in tools/registry.

Tiny adjustment to vcpkg configuration

---

.gitmodules
CMakeLists.txt
vcpkg-configuration.json
vcpkg.json

Long term we'll be moving away from using libalgebra-lite as an external module and incorporating the functionality into RoughPy directly so it doesn't make sense to make it a regular dependency.

Revert to libalgebra-lite submodule rather than using vcpkg

---

algebra/src/lite_context.h
tests/streams/test_lie_increment_path.py

Fixed a bug caused by passing a wider than expected array to stream construction. Closes #70.

Fix fault constructing larger than expected array

---

README.md

Fix the link to the tensor_functions.py file in the README to actually point to the file.
Closes #74

Change the link in README to point to folder

---

roughpy/src/algebra/basis.cpp
roughpy/src/algebra/context.cpp

Fixed a couple of problems resulting from the (lack of) default arguments for the basis.size method and context.(tensor|lie)_size method.
Both methods now have a default argument which queries the size at the maximum degree of the algebra. If the user requests an degree larger than the depth, an exception is thrown. If the requested degree is negative, the maximum degree is requested.
Closes #75 and closes #76

Fix degree argument on basis size

---

roughpy/src/intervals/partition.cpp
tests/intervals/test_partitions.py

Fix Partition intermediate points not being filtered to contain only those within the base interval and not being sorted.
Closes #80

Fix partition intermediates unchecked

---

pyproject.toml
roughpy/CMakeLists.txt
roughpy/src/algebra/context.cpp
roughpy/src/args/check_for_excess_args.cpp
roughpy/src/args/kwargs_to_path_metadata.cpp
roughpy/src/args/kwargs_to_path_metadata.h
roughpy/src/args/kwargs_to_vector_construction.cpp
roughpy/src/args/kwargs_to_vector_construction.h
roughpy/src/args/parse_algebra_configuration.cpp
roughpy/src/args/parse_algebra_configuration.h
roughpy/src/roughpy_module.h
roughpy/src/streams/brownian_stream.cpp
roughpy/src/streams/externally_sourced_stream.cpp
roughpy/src/streams/function_stream.cpp
roughpy/src/streams/lie_increment_stream.cpp
roughpy/src/streams/piecewise_abelian_stream.cpp
roughpy/src/streams/schema_finalization.cpp
roughpy/src/streams/tick_stream.cpp
streams/include/roughpy/streams/schema.h
streams/src/external_data_sources/sound_file_data_source.cpp
streams/src/schema.cpp
tests/streams/test_lie_increment_path.py

Overhauled the handling of keyword arguments in constructors for streams and algebra types.
All of these constructors now make use of the new `parse_algebra_configuration` function to get the context or width-depth-scalar_type combination. Moreover, the `width`, `depth`, and `dtype` arguments are now deprecated, and a warning is produced to tell the user to use `ctx` instead.
In addition, a mechanism has been put in place to check that all the keyword arguments have been consumed, and raising an exception if not,
Closes #77

Fix unknown keyword arguments not flagged

---

roughpy/src/algebra/setup_algebra_type.h

Add an optional 'copy' parameter to the '__array__' method in the Alg class for better control over numpy array. This parameter defaults to false, maintaining current behavior while providing flexibility for future modifications.

Enhance numpy conversion in Alg class

---

.github/workflows/build_wheels.yml

Enabled the workflow_dispatch event to allow manual triggering of the build wheels workflow. This provides more flexibility for testing and deployment without requiring a new tag push.

Add manual workflow trigger in build_wheels.yml

---

.github/workflows/build_wheels.yml
pyproject.toml

Updated pyproject.toml to include classifiers for Python 3.12 and 3.13. Modified GitHub workflow to use Python 3.13 and updated cibuildwheel action and macOS deployment target to the latest versions.
closes #105

Add support for Python 3.12 and 3.13

---

.github/workflows/build_wheels.yml
.github/workflows/tests.yml
CMakeLists.txt
CMakePresets.json
intervals/src/interval.cpp
roughpy/_roughpy.pyi
roughpy/src/algebra/setup_algebra_type.h
roughpy/src/intervals/dyadic_interval.cpp
streams/CMakeLists.txt
tests/algebra/test_free_multiply_functions.py
tests/intervals/test_dyadic_interval.py
tests/scalars/dlpack/test_construct_from_jax.py
vcpkg-configuration.json
vcpkg.json

Fixes #95 
- Original issue fixed by adding default arguments for resolution (32) and interval type (IntervalType::Clopen). 
- Additional issue with contains function implementations also fixed. 
- Added all cpp tests to pytest, with skips for incomplete implementations

95 using dyadicintervalto dyadic intervals with realinterval throws an error

---

.github/dependabot.yml
.github/workflows/build_wheels.yml
.github/workflows/tests.yml
pyproject.toml

Moved some of the configuration environment variables out of the build_wheels build and into the pyproject.toml. Hopefully the improvements to the build system will allow us to build more flexibly.

Remove debug configuration and tidy up actions file.

---

.gitignore

This addition prevents the .gdbinit file from being tracked by Git. It ensures that any GDB configurations used during development remain local to the developer's environment.

Add .gdbinit to .gitignore

---

roughpy/src/args/buffer_info.h

This commit updates the BufferInfo class to make the m_view member mutable. This change is necessary because the Python API consistently passes mutable pointers, and we need to reflect that in our code structure.

Make BufferInfo's Py_buffer mutable

---

.github/dependabot.yml
.github/workflows/build_wheels.yml
.github/workflows/tests.yml

Updated the tests runner to ignore more files that don't affect the build/testing of RoughPy. Changed the matrix to include MacOS13 and 14 so that wheels are built for Apple Silicon too.
Fixed missing build tool installs on macOS.

Fix GitHub actions again

---

.github/workflows/build_wheels.yml

Modified the 'Retrieve wheels' step to use a specific pattern ("cibw-*") and enabled merge-multiple to true. This ensures that multiple artifacts matching the pattern are merged correctly during the download.

Update wheel retrieval in GitHub workflow

---

core/include/roughpy/core/alloc.h

Introduce two templated `construct_inplace` functions in alloc.h to facilitate object construction directly in allocated memory. These functions enhance flexibility by supporting both pointer and reference types as the destination for in-place constructions.

Add templated construct_inplace functions

---

.github/workflows/tests.yml

The tests action should be runnable on demand, not just on pull requests/pushes to main

Add ability to launch manually

---

docs/source/_static/terry-trimmed.mp4
docs/source/_static/terry.mp4

The video files used in the documentation are causing problems with the version control. I've removed them.

Remove videos because they are too large

---

algebra/src/libalgebra_lite_internal/tensor_basis_info.h
roughpy/src/algebra/lie.cpp
roughpy/src/algebra/shuffle_tensor.cpp
roughpy/src/args/kwargs_to_path_metadata.cpp
roughpy/src/args/parse_data_argument.cpp
scalars/src/key_scalar_array.cpp
scalars/src/scalar.cpp
scalars/src/scalar/comparison.cpp
scalars/src/scalar_helpers/standard_scalar_type.h
streams/src/schema.cpp

Turning on `-Wal`l highlighted a number of comparisons of diffrent signedness. I've fixed these by one argument to the other type. This is not a good fix, but it is a good stand-in for now until better mechanisms are available.

fix-different-signedness-comparisons

---

cmake/developer_options_setup.cmake

Clang has a mode that allows it to trace various aspects of the compilation progress. This simply constructs a json file containing details of the build alongside the built artifacts that can be opened in chrome tracing (in any chrome based browser).

Add profiling option with Clang via -ftime-trace

---

testing/CMakeLists.txt
testing/src/main.cpp

Create a `RoughPy_test_harness` library to customize Google Test's main function. This includes redirecting debug output to stderr, which avoids using default debug popups. The `CMakeLists.txt` was updated to link this new library instead of the default gtest main.

Add test harness for Windows debug mode in gtest setup

---

algebra/include/roughpy/algebra/basis.h
algebra/include/roughpy/algebra/context.h
algebra/include/roughpy/algebra/context_fwd.h
algebra/include/roughpy/algebra/linear_operator.h
algebra/src/context.cpp
core/CMakeLists.txt
core/include/roughpy/core/smart_ptr.h
platform/include/roughpy/platform/devices/core.h
platform/include/roughpy/platform/devices/device_handle.h
platform/src/devices/device_handle.cpp
platform/src/devices/host/host_decls.h
platform/src/devices/host/host_device_impl.cpp
platform/src/devices/opencl/ocl_decls.h

Boost intrusive pointers might not be the way we want to keep smart pointers in the future, so we have made an alias for them. This should make it easier to replace it in the future if necessary

Overhaul memory smart pointer

---

cmake/component_setup.cmake
platform/src/devices/CMakeLists.txt
streams/src/channels/CMakeLists.txt

Adjusted the include directory paths in `cmake/component_setup.cmake`, `platform/src/devices/CMakeLists.txt`, and `streams/src/channels/CMakeLists.txt` for consistency and correctness. This ensures that the correct directories are referenced during the build process.

Fix component include directory paths set by cmake function

---

core/include/roughpy/core/check.h
platform/src/errors.cpp

The throw_exception function had its [[noreturn]] attribute removed, which lead to a number of compiler warnings about non-returning functions after a throw.

Added RPY_NO_RETURN attribute to throw_exception

---

testing/src/main.cpp

The function was missing a return statement, which could lead to undefined behavior. This change ensures the function returns the intended result consistently.

Add missing return statement in main.cpp

---

platform/include/roughpy/platform/alloc.h
platform/src/CMakeLists.txt
platform/src/alloc.cpp
platform/src/generics/CMakeLists.txt
platform/src/test_alloc.cpp

Lots of RoughPy objects are small and allocated frequently. We add a pool allocator to the Platform to facilitate this.

Feature small objects

---

.github/workflows/tests.yml
algebra/CMakeLists.txt
intervals/CMakeLists.txt
platform/CMakeLists.txt
roughpy/CMakeLists.txt
scalars/CMakeLists.txt
streams/CMakeLists.txt
streams/src/schema.cpp

The build performance of RougPy is somewhat lacking, especially on Windows where we have to use MSVC (by far the slowest compiler of the three). To combat this, we define a new PrecompiledHeaders target that we can link to that contains all the private headers that we need all over the place in RoughPy that take a lot of time to process. This mainly consists of cereal, which ultimately we want to remove because it is so expensive to instantiate, and a pain to integrate across API boundaries. (Removing this is somewhat down the line.)

Fix build time performance improvements

---

platform/include/roughpy/generics/comparison_trait.h
platform/include/roughpy/generics/number_trait.h
roughpy/src/algebra/lie_key.cpp

Clang threw some warnings about using abs on a non-signed type. Created a new specialisation of the implementation that does nothing to unsigned integral types.
Also added [[maybe_unused]] to a couple of private class members that are currently unused, but need to be there.

Fix compiler warnings from unncessary abs

---

platform/include/roughpy/generics/type.h
platform/include/roughpy/generics/values.h
platform/src/generics/builtin_types/builtin_type.h
platform/src/generics/builtin_types/builtin_type_methods.h
platform/src/generics/builtin_types/test_double_type.cpp
platform/src/generics/builtin_types/test_float_type.cpp
platform/src/generics/test_value.cpp
platform/src/generics/type.cpp
platform/src/generics/value.cpp

As we shift to a "hidden implementation" model for the more complicated scalar types like rationals and a poly rationals, we need a robust means for users to actually construct and use these types. One of the easiest means will be to have a parser that can parse a string into a value (e.g. `"{ 1(x0) 1(x2) }"` would parse to a polynomial whose string representation is the given. 
This PR adds the interface to the Type class and to the Value type that allows for this.

Feature parse value from string

---

CMakeLists.txt
platform/include/roughpy/generics/type.h
platform/src/generics/CMakeLists.txt
platform/src/generics/multiprecision_types/mpq_string_rep.h
platform/src/generics/multiprecision_types/mpz_hash.h
platform/src/generics/multiprecision_types/rational_type.cpp
platform/src/generics/polynomial_type/CMakeLists.txt
platform/src/generics/polynomial_type/indeterminate.cpp
platform/src/generics/polynomial_type/indeterminate.h
platform/src/generics/polynomial_type/monomial.cpp
platform/src/generics/polynomial_type/monomial.h
platform/src/generics/polynomial_type/polynomial.cpp
platform/src/generics/polynomial_type/polynomial.h
platform/src/generics/polynomial_type/polynomial_arithmetic.cpp
platform/src/generics/polynomial_type/polynomial_arithmetic.h
platform/src/generics/polynomial_type/polynomial_comparison.cpp
platform/src/generics/polynomial_type/polynomial_comparison.h
platform/src/generics/polynomial_type/polynomial_number.cpp
platform/src/generics/polynomial_type/polynomial_number.h
platform/src/generics/polynomial_type/polynomial_type.cpp
platform/src/generics/polynomial_type/polynomial_type.h
platform/src/generics/polynomial_type/test_indeterminate.cpp
platform/src/generics/polynomial_type/test_monomial.cpp
platform/src/generics/polynomial_type/test_polynomial.cpp
platform/src/generics/polynomial_type/test_polynomial_type.cpp
platform/src/generics/polynomial_types.cpp
vcpkg.json

This adds basic support for polynomial coefficients. This is part of the generic values overhaul outlined in #168.
To support the string parsing, I've brought in CTRE (compile time regular expressions) to avoid using `<regex>` which is dreadfully slow and tricky to use. I've also brought in `fmt` because it will be useful.

Overhaul polynomial type

---

vendored/libalgebra_lite/index_key.h

The index_key is used for basis keys for libalgebra_lite tensors and Lie algebras. The default number of bits was set to 4, meaning a maximum of degree 15 for basis keys. This is probably the source of numerous errors in RoughPy when using degree >= 16. This change fixes the number of bits to 8, giving a maximum of degree 255, which should be completely sufficient until we can finally get rid of libalgebra_lite and replacing the badness within

Fixed the degree bits in the libalgebra lite index_key type

---

roughpy/src/algebra/context.cpp

Width 0 or depth 0 are not well-behaved cases in RoughPy. This PR adds checks to the `get_context` function to ensure that these are properly reported as erroneous. For the time being, these cases must be treated as undefined behaviour, and thus should not be used. Our position on this may change in the future. Closes #177.

Add validation checks for width and depth in context creation

---

roughpy/src/args/parse_data_argument.cpp
roughpy/src/streams/tensor_valued_stream.cpp
streams/include/roughpy/streams/lie_increment_stream.h
streams/src/lie_increment_stream.cpp
streams/src/tensor_valued_stream.cpp
tests/streams/test_tensor_valued_stream.py

This PR adds a new constructor function for tensor valued streams that takes a sequence of (group-like) tensors (or Lie elements). This is implemented as a class function `from_values` on the `TensorValuedStream` class in the Python interface.

Feat value list constructor for value

---

.github/workflows/tests.yml

There are several problems with the GitHub actions. The first, and probably most serious, is that the cached artefacts from previous builds are not used when running tests on new PRs currently. This is devastating on Windows where building all the dependencies take ~25 minutes. This eats up a lot of compute time but also really hinders fast iterations where one creates multiple PRs in quick succession.
I've re-enabled the tests on push to main, which should do two things. Fist, it will trigger workflows whenever main is updated (which should only occur on merged PRs anyway) and it will build cache entries on the main branch, where they can be reused in others. (All actions on a repo have access to the default branch https://docs.github.com/en/actions/writing-workflows/choosing-what-your-wo …

Fix various things with the GitHub actions

---

.github/workflows/update-dependencies.yml

This workflow triggers on changes to vcpkg.json or vcpkg-configuration.json in the main branch. It sets up vcpkg, bootstraps it, and performs a dry-run to build the dependency graph. This ensures dependency updates are tracked and managed automatically.

Add GitHub workflow to update vcpkg dependencies

---

roughpy/src/streams/lie_increment_stream.cpp
tests/streams/test_lie_increment_path.py

The esig interface exposed a bug in which not specifying the support would cause an infinite loop as the dyadic intervals over the unbounded interval [0, +inf) were enumerated in the case where no increments were provided to stream constructor. This is caused by the construct setting the unbounded interval as the default value, which is usually overwritten by either the additional arguments or is inferred from the timestamps during the construction process. Of course, both fail is the support is not provided and no data is provided. This is now fixed by setting the effective support to [0, 1).

Fix infinite loop if support not specified

---

streams/src/stream.cpp
tests/streams/test_lie_increment_path.py

The internals of Lie increment path have changed somewhat leading to a problem whereby requesting a signature over the unit interval with resolution 0, does not provide the correct answer. The problem is that internally the query interval is trimmed to without an adjusted resolution. This PR fixes this issue.

Fix bug signature domain

---

.github/workflows/build_wheels.yml
.github/workflows/tests.yml
CMakeLists.txt
roughpy/CMakeLists.txt
tools/ci/before-all-common.sh
vcpkg.json

Fixed a couple of CMake errors that prevented the install step working in the wheel building.
Also fixed a couple of small issues in the actions.

Fix install path cmake

---

CMakeLists.txt
platform/src/alloc.cpp
vcpkg.json

Older versions of libc++, such as those found on MacOs <14, don't implement `std::pmr::memory_resource`, but for some reason still compiles and links. This leads to a rather frustrating missing symbol error at load-time, causing the program to fail unexpectedly. For this reason, I've swapped out the `std::pmr::synchronized_pool_allocator` for a `boost::pool` that also provides a pool-style allocator that we can use for small objects. I don't know if this functions in precisely the same way was the std version, but at least it is platform independent and faster than "malloc"ing everything.

Fix pool allocator

---

.github/workflows/build_wheels.yml
.github/workflows/tests.yml
platform/CMakeLists.txt
pyproject.toml
tools/ci/before-all-common.sh

The wheel action needed an update to make it use Ninja on Windows; MSBuild is painfully slow and Ninja makes this run much faster. Bringing over the settings from the test action made the build fail. It turned out that Visual studio brought it's own version of VCPKG that was being used preferentially because VCPKG_ROOT was not set in the wheels action. This caused the installation of dependencies to fail (out-of-date vcpkg or something more sinister). This is fixed by setting the toolchain explicitly, like in the tests action. For some reason, this makes the installation successful.

Fix build wheel action

---

roughpy/src/args/kwargs_to_path_metadata.cpp
roughpy/src/streams/tensor_valued_stream.cpp
streams/src/tensor_valued_stream.cpp
tests/streams/test_tensor_valued_stream.py

I've added a new test for the value stream that tests that the value-stream as the solution to the signature CDE behaves correctly. This also fixes some minor issues in the constructor.

New test for value stream

---

.github/workflows/tests.yml
CMakeLists.txt
CMakePresets.json
algebra/src/CMakeLists.txt
cmake/Modules/FindGMP.cmake
cmake/Modules/FindMPFR.cmake
cmake/Modules/FindPCGRandom.cmake
cmake/roughpy_helpers.cmake
cmake/vcpkg_setup.cmake
conandata.yml
conanfile.py
platform/CMakeLists.txt
platform/src/generics/multiprecision_types/CMakeLists.txt
platform/src/generics/polynomial_type/CMakeLists.txt
platform/src/generics/polynomial_type/polynomial_type.cpp
pyproject.toml
scalars/CMakeLists.txt

Vcpkg is a rather frustrating package manager. It's slow and often has problems with its ports not being updated frequently enough. Unfortunately, we've built the ecosystem around using vcpkg, which has started to cause some problems. This PR adds support for using conan as a package manager instead. This shouldn't break the existing vcpkg support, but it will make using the build system somewhat easier.

Add conan build support

---

roughpy/compute/_src/dense_basic.cpp
roughpy/compute/_src/lie_basis.c
roughpy/compute/_src/py_binary_array_fn.hpp
roughpy/compute/_src/py_ternary_array_fn.hpp
roughpy/compute/_src/tensor_basis.c

This pull request addresses several bugs in the initial commit of the free-standing-compute components.
- Updated to use `Py_INCREF` for compatibility with Python < 3.10.
- Fixed reference assignment and parameter initialization in `TensorBasis` and `LieBasis` to ensure proper memory handling.
- Resolved keyword argument mismatch in inplace multiplication.
- Corrected type checks in `py_binary_array_fn` and `py_ternary_array_fn` to validate NumPy array inputs properly.
- Guaranteed initialization of `index` arrays in `py_binary_array_fn` and `py_ternary_array_fn` to ensure consistent behavior.
- Fixed missing argument parsing in `ft_fma`.

Fix various compatibility and stability issues in Python functions
